name: Docker

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
      - name: Push Docker image
        run: |
          docker tag myapp:latest ${{ env.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ env.DOCKER_USERNAME }}/myapp:latest
